sudo: required
language: python

matrix:
    include:
        - python: "3.4"
          os: linux
          dist: trusty
        - python: "3.5"
          os: linux
          dist: xenial
        - python: "3.6"
          os: linux
          dist: bionic
        - python: "3.7"
          os: linux
          dist: bionic
        - python: "3.8"
          os: linux
          dist: focal
        - python: "3.9-dev"
          os: linux
          dist: focal

addons:
  apt:
    packages:
    - libattr1-dev
    - pkg-config
    - gcc
    - libfuse-dev
install: test/travis-install.sh
script: test/travis-test.sh
